import Head from 'next/head'
import Banner from '../components/Banner/Banner'
import Card from '../components/Card/Card'
import SectionCards from '../components/Card/SectionCards'
import Navbar from '../components/Nav/Navbar'

import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar username="Jason"/>
      <Banner title="Clifford" subtitle="Subtitle test, very testy" imgUrl="/static/clifford.webp"/>

      <div  className={styles.sectionWrapper}>

        <SectionCards title="Disney" />
      </div>

    </div>
  )
}
