import Head from 'next/head'
import Banner from '../components/Banner/Banner'
import Navbar from '../components/Nav/Navbar'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar username="Jason"/>
      <Banner title="Clifford" subtitle="Subtitle test, very testy" imgUrl="/static/clifford.webp"/>
    </div>
  )
}
